# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [Death, beloved]
patreon: # Replace with a single Patreon username mouse3687
open_collective: # Replace with a single Open Collective username hunterz.io
ko_fi: # Replace with a single Ko-fi username mouse3687
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username king daughters 
issuehunt: # Replace with a single IssueHunt username catfish
otechie: # Replace with a single Otechie username NOGO
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['https://golo.com','https://www.truthinadvertising.org/knightline-legal/','https://iab.org','https://www.dhs.gov/news/2018/01/23/dhs-issues-waiver-expedite-border-construction-project-new-mexico','https://chime.com']
